
export const allDishes = [
    {keyword: 'borzh-russian-soup',
        name: 'Борщ русский',
        price: 195,
        category: 'soups',
        count: '350g',
        image: './soups/borzh.jpeg',
        kind: 'meat'
    },
        {keyword: 'schi-soup',
        name: 'Щи',
        price: 380,
        category: 'soups',
        count: '459g',
        image: './soups/schi_v2.jfif',
        kind: 'meat',
    },
        {keyword: 'mushroom-soup',
        name: 'Грибной суп',
        price: 380,
        category: 'soups',
        count: '450g',
        image: './soups/mushroom-soup.jpg',
        kind: 'veg',
    },
        {keyword: 'buckwheat-main-dish',
        name: 'Гречка',
        price: 180,
        category: 'main-dish',
        count: '280g',
        image: './main-dishes/grechka.jpg',
        kind: 'veg',
    },
        {keyword: 'soup-hekka',
        name: 'Рыбный суп Хекка',
        price: 350,
        category: 'soups',
        count: '280g',
        image: './soups/fish-soup-heka.jpg',
        kind: 'fish',
    },
        {keyword: 'soup-mintay',
        name: 'Рыбный суп из минтая',
        price: 350,
        category: 'soups',
        count: '280g',
        image: './soups/fish-soup-mentay.jpg',
        kind: 'fish',
    },
        {keyword: 'soup-korean',
        name: 'Корейский суп на говяжьем бульоне',
        price: 350,
        category: 'soups',
        count: '280g',
        image: './soups/korean-soup.webp',
        kind: 'meat',
    },
        {keyword: 'soup-solyanka',
        name: 'Солянка на говяжьем бульоне',
        price: 425,
        category: 'soups',
        count: '300g',
        image: './soups/selyanka.webp',
        kind: 'meat',
    },
        {keyword: 'soup-brokkoli',
        name: 'Суп из броколей',
        price: 325,
        category: 'soups',
        count: '300g',
        image: './soups/veg-soup-brokkoli.jpg',
        kind: 'veg',
    },
        {keyword: 'soup-tomato',
        name: 'Томатный суп на мясном бульоне',
        price: 305,
        category: 'soups',
        count: '30g',
        image: './soups/veg-tomato-soup.jpg',
        kind: 'veg',
    },
    {keyword: 'pilaf-main-dish',
        name: 'Плов',
        price: 380,
        category: 'main-dish',
        count: '180g',
        image: './main-dishes/plov.webp',
        kind: 'meat',
    },
        {keyword: 'dumplings-main-dish',
        name: 'Пельмени',
        price: 380,
        category: 'main-dish',
        count: '180g',
        image: './main-dishes/pelmeni.jpg',
        kind: 'meat'
    },
        {keyword: 'spagetti-main-dish',
        name: 'Спагетти по флоцки',
        price: 280,
        category: 'main-dish',
        count: '230g',
        image: './main-dishes/spagetti-flocsi.webp',
        kind: 'meat'
    },
        {keyword: 'ragu-main-dish',
        name: 'Тушеное рагу с овощами',
        price: 230,
        category: 'main-dish',
        count: '235g',
        image: './main-dishes/ragu-vegetables.jpg',
        kind: 'veg'
    },
        {keyword: 'baklazany-main-dish',
        name: 'Баклажаны Пармеджано',
        price: 300,
        category: 'main-dish',
        count: '295g',
        image: './main-dishes/baklazany.jpeg',
        kind: 'veg'
    },
        {keyword: 'grecian-fish-main-dish',
        name: 'Тушёная рыба по-Гречески',
        price: 300,
        category: 'main-dish',
        count: '295g',
        image: './main-dishes/grecian-fish.jpg',
        kind: 'fish'
    },
        {keyword: 'poland-fish-main-dish',
        name: 'Рыба по-Польски',
        price: 300,
        category: 'main-dish',
        count: '295g',
        image: './main-dishes/polski-fish.jpg',
        kind: 'fish'
    },
        {keyword: 'conservs-salad',
        name: 'Салат с рыбными консервами, яйцом',
        price: 180,
        category: 'salads',
        count: '255g',
        image: './salates|starters/firstSalad.jpg',
        kind: 'fish'
    },
        {keyword: 'mimoza-salad',
        name: 'Салат "Мимоза"',
        price: 230,
        category: 'salads',
        count: '225g',
        image: './salates|starters/mimozaSalad.jpg',
        kind: 'fish'
    },
        {keyword: 'sunrise-salad',
        name: 'Салат "Восход солнца"',
        price: 230,
        category: 'salads',
        count: '225g',
        image: './salates|starters/sunriseSatad.jpg',
        kind: 'fish'
    },
        {keyword: 'italian-salad',
        name: 'Мясной салат по-Итальянски',
        price: 220,
        category: 'salads',
        count: '195g',
        image: './salates|starters/meateggSalad.jpg',
        kind: 'meat'
    },
        {keyword: 'heap-salad',
        name: 'Салат "Куча" с свиным фаршем',
        price: 250,
        category: 'salads',
        count: '195g',
        image: './salates|starters/minceSalad.jpg',
        kind: 'meat'
    },
        {keyword: 'onion-salad',
        name: 'Салат с маринованным луком',
        price: 250,
        category: 'salads',
        count: '195g',
        image: './salates|starters/paperSalad.jpg',
        kind: 'meat'
    },
        {keyword: 'grecian-salad',
        name: 'Греческий салат с тофу',
        price: 250,
        category: 'salads',
        count: '195g',
        image: './salates|starters/tofu-salad.jpg',
        kind: 'veg'
    },
        {keyword: 'olivie-salad',
        name: 'Вегетарианский ольвие',
        price: 220,
        category: 'salads',
        count: '235g',
        image: './salates|starters/olivie-salad.jpg',
        kind: 'veg'
    },
        {keyword: 'vinegdet-salad',
        name: 'Классический винегрет',
        price: 250,
        category: 'salads',
        count: '195g',
        image: './salates|starters/vinegdet-salad.jpg',
        kind: 'veg'
    },

        {keyword: 'semga-main-dish',
        name: 'Сёмга в сливочном соусе',
        price: 310,
        category: 'main-dish',
        count: '295g',
        image: './main-dishes/semga.jpg',
        kind: 'fish'
    },
        {keyword: 'orange-juice-drink',
        name: 'Апельсиновый сок',
        price: 120,
        category: 'drinks',
        count: '180ml',
        image: './drinks/orange-juice.webp',
        kind: 'cold-drinks'
    },
    {keyword: 'black-tea-drink',
        name: 'Чёрный чай',
        price: 80,
        category: 'drinks',
        count: '180ml',
        image: './drinks/black-tea.jpg',
        kind: 'hot-drinks'
    },
    {keyword: 'lemonade-drink',
    name: 'Лимонад',
    price: 150,
    category: 'drinks',
    count: '180ml',
    image: './drinks/lemonade.jpg',
    kind: 'cold-drinks'
    },
    {keyword: 'greentea-drink',
    name: 'Зеленый чай',
    price: 150,
    category: 'drinks',
    count: '180ml',
    image: './drinks/green-tea.jpg',
    kind: 'hot-drinks'
    },
    {keyword: 'carcadetea-drink',
    name: 'Чай каркаде',
    price: 160,
    category: 'drinks',
    count: '180ml',
    image: './drinks/carcade-tea.jpg',
    kind: 'hot-drinks'
    },
    {keyword: 'tomatojuice-drink',
    name: 'Томатный сок',
    price: 120,
    category: 'drinks',
    count: '130ml',
    image: './drinks/tomato-juice.jpg',
    kind: 'cold-drinks'
    },
    {keyword: 'pahvala-dessert',
    name: 'Пахвала с орешками',
    price: 150,
    category: 'desserts',
    count: '130g',
    image: './desserts/pahvala.jpg',
    kind: 'small'
    },
    {keyword: 'cake-chocolate-dessert',
    name: 'Шоколадный торт',
    price: 150,
    category: 'desserts',
    count: '130g',
    image: './desserts/cake.jpg',
    kind: 'small'
    },
    {keyword: 'donut-dessert',
    name: 'Полицейский пончик',
    price: 150,
    category: 'desserts',
    count: '130g',
    image: './desserts/donut.jpg',
    kind: 'medium'
    },
    {keyword: 'berrycake-dessert',
    name: 'Ягодный торт',
    price: 150,
    category: 'desserts',
    count: '130g',
    image: './desserts/cake-berry.jpg',
    kind: 'medium'
    },
    {keyword: 'chococale-dessert',
    name: 'Шоколадный торт (большой)',
    price: 150,
    category: 'desserts',
    count: '130g',
    image: './desserts/chococale-cake.webp',
    kind: 'big'
    },
    {keyword: 'waffles-dessert',
    name: 'Медовые вафли',
    price: 150,
    category: 'desserts',
    count: '130g',
    image: './desserts/waffles.jpg',
    kind: 'big'
    },
];